Fix: BLF leaks memory leak on exit
Resolve leak on exit, caused by !147733.

----

This resolves a leak, I should have caught this in review, from checking #147168,
the issue is still fixed after this change.

```
blender -d --factory-startup
... exit blender ...
Error: Not freed memory blocks: 1, total unfreed memory 0.000130 MB
GLStorageBuf len: 136 0x7ca7662601c0
```

Pull Request: https://projects.blender.org/blender/blender/pulls/148475